version: 0-{branch}+{build}

shallow_clone: true

environment:
  MIX_ENV: test

install:
  - ps: Start-FileDownload "https://github.com/elixir-lang/elixir/releases/download/v1.4.2/Precompiled.zip"
  - 7z x -oelixir Precompiled.zip
  - SET PATH=%PATH%;C:\Program Files\erl8.3\bin

cache:
  - deps

build_script:
  - elixir/bin/mix local.hex --force
  - elixir/bin/mix local.rebar --force
  - elixir/bin/mix deps.get
  - elixir/bin/mix compile

before_test:
  SET PATH=%PATH%;C:\MinGW\msys\1.0\bin

test_script:
  elixir/bin/mix test
